version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: crateuser
      POSTGRES_PASSWORD: cratesenha
      POSTGRES_DB: cratecloud
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  backend:
    build: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./:/app                      
      - ./downloads:/app/downloads 
    environment:
      - DATABASE_URL=postgresql://crateuser:cratesenha@db:5432/cratecloud
    depends_on:
      - db

volumes:
  pgdata:
